package com.ctvit.auth.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * 
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {

	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("system_permission", "pk", SystemPermission.class);
		arp.addMapping("system_role", "pk", SystemRole.class);
		arp.addMapping("system_role2permission", "pk", SystemRole2permission.class);
		arp.addMapping("system_user", "pk", SystemUser.class);
		arp.addMapping("system_user2role", "pk", SystemUser2role.class);
	}
}
