package com.ctvit.auth.model;

import com.ctvit.auth.model.base.BaseSystemRole2permission;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SystemRole2permission extends BaseSystemRole2permission<SystemRole2permission> {
	public static final SystemRole2permission dao = new SystemRole2permission();
}
