package com.ctvit.auth.model;

import com.ctvit.auth.model.base.BaseSystemRole;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SystemRole extends BaseSystemRole<SystemRole> {
	public static final SystemRole dao = new SystemRole();
}
