package com.ctvit.auth.model;

import com.ctvit.auth.model.base.BaseSystemPermission;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SystemPermission extends BaseSystemPermission<SystemPermission> {
	public static final SystemPermission dao = new SystemPermission();
}
