package com.ctvit.auth.model;

import com.ctvit.auth.model.base.BaseSystemUser;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SystemUser extends BaseSystemUser<SystemUser> {
	public static final SystemUser dao = new SystemUser();
}
