package com.ctvit.auth.model;

import com.ctvit.auth.model.base.BaseSystemUser2role;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SystemUser2role extends BaseSystemUser2role<SystemUser2role> {
	public static final SystemUser2role dao = new SystemUser2role();
}
