package com.ctvit.auth.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSystemPermission<M extends BaseSystemPermission<M>> extends Model<M> implements IBean {

	public void setPk(java.lang.Integer pk) {
		set("pk", pk);
	}

	public java.lang.Integer getPk() {
		return get("pk");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}

	public java.lang.String getName() {
		return get("name");
	}

	public void setUrl(java.lang.String url) {
		set("url", url);
	}

	public java.lang.String getUrl() {
		return get("url");
	}

	public void setParentPk(java.lang.Integer parentPk) {
		set("parent_pk", parentPk);
	}

	public java.lang.Integer getParentPk() {
		return get("parent_pk");
	}

	public void setState(java.lang.Boolean state) {
		set("state", state);
	}

	public java.lang.Boolean getState() {
		return get("state");
	}

}
