package com.ctvit.auth.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSystemUser<M extends BaseSystemUser<M>> extends Model<M> implements IBean {

	public void setPk(java.lang.Integer pk) {
		set("pk", pk);
	}

	public java.lang.Integer getPk() {
		return get("pk");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}

	public java.lang.String getName() {
		return get("name");
	}

	public void setNameCh(java.lang.String nameCh) {
		set("name_ch", nameCh);
	}

	public java.lang.String getNameCh() {
		return get("name_ch");
	}

	public void setPassword(java.lang.String password) {
		set("password", password);
	}

	public java.lang.String getPassword() {
		return get("password");
	}

	public void setEmail(java.lang.String email) {
		set("email", email);
	}

	public java.lang.String getEmail() {
		return get("email");
	}

	public void setGender(java.lang.Boolean gender) {
		set("gender", gender);
	}

	public java.lang.Boolean getGender() {
		return get("gender");
	}

	public void setState(java.lang.Boolean state) {
		set("state", state);
	}

	public java.lang.Boolean getState() {
		return get("state");
	}

}
