package com.ctvit.auth.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSystemUser2role<M extends BaseSystemUser2role<M>> extends Model<M> implements IBean {

	public void setPk(java.lang.Integer pk) {
		set("pk", pk);
	}

	public java.lang.Integer getPk() {
		return get("pk");
	}

	public void setUserPk(java.lang.Integer userPk) {
		set("user_pk", userPk);
	}

	public java.lang.Integer getUserPk() {
		return get("user_pk");
	}

	public void setRolePk(java.lang.Integer rolePk) {
		set("role_pk", rolePk);
	}

	public java.lang.Integer getRolePk() {
		return get("role_pk");
	}

}
