package com.ctvit.auth.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSystemRole2permission<M extends BaseSystemRole2permission<M>> extends Model<M> implements IBean {

	public void setPk(java.lang.Integer pk) {
		set("pk", pk);
	}

	public java.lang.Integer getPk() {
		return get("pk");
	}

	public void setRolePk(java.lang.Integer rolePk) {
		set("role_pk", rolePk);
	}

	public java.lang.Integer getRolePk() {
		return get("role_pk");
	}

	public void setPermissionPk(java.lang.Integer permissionPk) {
		set("permission_pk", permissionPk);
	}

	public java.lang.Integer getPermissionPk() {
		return get("permission_pk");
	}

}
